#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Nov 23 14:39:08 2011

import wx

# begin wxGlade: extracode
import excel
import win32com.client
# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.label_UID = wx.StaticText(self, -1, _("UID:"))
        self.UID = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)
        self.label_StuName = wx.StaticText(self, -1, _("Name: "))
        self.StuName = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY|wx.TE_RIGHT)
        self.label_StuMark = wx.StaticText(self, -1, _("Marks:"))
        self.Marks = wx.TextCtrl(self, -1, "", style=wx.TE_RIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.uid_change, self.UID)
        self.Bind(wx.EVT_TEXT, self.uid_change, self.UID)
        self.Bind(wx.EVT_TEXT_ENTER, self.mark_change, self.Marks)
        self.Bind(wx.EVT_TEXT, self.mark_change, self.Marks)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Excel Search and Replace"))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.label_UID.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.UID.SetMinSize((450, 60))
        self.UID.SetFont(wx.Font(36, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.label_StuName.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.StuName.SetMinSize((450, 60))
        self.StuName.SetFont(wx.Font(36, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.label_StuMark.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.Marks.SetMinSize((450, 60))
        self.Marks.SetFont(wx.Font(36, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2_copy = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(self.label_UID, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.UID, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_StuName, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.StuName, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_2_copy.Add(self.label_StuMark, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2_copy.Add(self.Marks, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_2_copy.AddGrowableCol(0)
        grid_sizer_2_copy.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_2_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def uid_change(self, event): # wxGlade: MyFrame.<event_handler>
        result_list = excel.SearchString(col_1,str(self.UID.GetValue()))
        if len(result_list) == 0:
            self.StuName.ChangeValue('0 result...')
        elif len(result_list) == 1:
            self.StuName.ChangeValue(col_2[result_list[-1]])
            self.Marks.ChangeValue(str(mark_list[result_list[-1]]))
	    excel.Select_xCell(result_list[-1] + 3,1)
            mark_list[result_list[-1]] = self.Marks.GetValue()
        else:
            self.StuName.ChangeValue('>1 results')
        
    def mark_change(self, event): # wxGlade: MyFrame.<event_handler>
        result_list = excel.SearchString(col_1,str(self.UID.GetValue()))
        temp_str = self.Marks.GetValue()
	excel.Select_xCell(result_list[-1] + 3,5)
        excel.write_xCell(result_list[-1] + 3,5,temp_str,'F')
        
# end of class MyFrame

if __name__ == "__main__":
	import gettext
	gettext.install("app") # replace with the appropriate catalog name
	
	col_1 = excel.ToStr(excel.xCol(1)[2:-1])
	col_2 = excel.ToStr(excel.xCol(2)[2:-1])
	col_3 = excel.xCol(5)
	mark_list = excel.ToFloat(col_3[2:-1])
	
	app = wx.PySimpleApp(0)
	wx.InitAllImageHandlers()
	Body = MyFrame(None, -1, "")
	app.SetTopWindow(Body)
	Body.Show()
	app.MainLoop()
